export enum City {
  Tirana = 'Tirana',
  Andorra = 'Andorra la Vella',
  Yerevan = 'Yerevan',
  Vienna = 'Vienna',
  Baku = 'Baku',
  Minsk = 'Minsk',
  Brussels = 'Brussels',
  Sarajevo = 'Sarajevo',
  Sofia = 'Sofia',
  Zagreb = 'Zagreb',
  Nicosia = 'Nicosia',
  Prague = 'Prague',
  Copenhagen = 'Copenhagen',
  Tallinn = 'Tallinn',
  Helsinki = 'Helsinki',
  Paris = 'Paris',
  Tbilisi = 'Tbilisi',
  Berlin = 'Berlin',
  Athens = 'Athens',
  Budapest = 'Budapest',
  Reykjavik = 'Reykjavik',
  Dublin = 'Dublin',
  Rome = 'Rome',
  // NurSultan = 'Nur-Sultan',
  Pristina = 'Pristina',
  Riga = 'Riga',
  Vaduz = 'Vaduz',
  Vilnius = 'Vilnius',
  Luxembourg = 'Luxemburg',
  Valletta = 'Valletta',
  Chisinau = 'Chisinau',
  Monaco = 'Monaco',
  Podgoric = 'Podgoric',
  Amsterdam = 'Amsterdam',
  Skopje = 'Skopje',
  Oslo = 'Oslo',
  Warsaw = 'Warsaw',
  Lisbon = 'Lisbon',
  Bucharest = 'Bucharest',
  Moscow = 'Moscow',
  // San Marino = 'San Marino',
  Belgrade = 'Belgrade',
  Bratislava = 'Bratislava',
  Ljubljana = 'Ljubljana',
  Madrid = 'Madrid',
  Stockholm = 'Stockholm',
  Bern = 'Bern',
  Ankara = 'Ankara',
  Kyiv = 'Kyiv',
  London = 'London',
  Vatican = 'Vatican',
  // VaticanCity = 'Vatican City'
}

export type CityEnum = typeof City;
export const CityEnum = {
  ...City
};


